version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik_mynet
      - intranet2020
    deploy:
      placement:
         constraints:
           - node.role == manager
      labels:
        - "traefik.port=80"
        - "traefik.backend=intranet2020" #nama project
        - "traefik.frontend.rule=Host:intranet2020.biznetnetworks.com"
        - "traefik.docker.network=traefik_mynet"
networks:
  traefik_mynet:
    external: true
  intranet2020:
    external: true
